[[language]]
name = "typescript"
auto-format = true
formatter = { command = "npx", args = ["--offline", "prettier", "--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "npx", args = ["--offline", "prettier", "--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "npx", args = ["--offline", "prettier", "--parser", "typescript"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "npx", args = ["--offline", "prettier", "--parser", "css"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "npx", args = ["--offline", "prettier", "--parser", "json"] }

[[language]]
name = "swift"
auto-format = true
formatter = { command = "swift-format", args = ["format"] }

[[language]]
name = "python"
# language-servers = ["pylsp"]
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"]}
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

# [language-server.pylsp.config.pylsp]
# # If necessary, maybe install with:
# #   pip install -U 'python-lsp-server[all]'
# plugins.ruff.enabled = true
# plugins.black.enabled = true

# [language-server.pylsp.config.pylsp]
# plugins.black.enabled = true
# plugins.pylsp_mypy.enabled = true
# plugins.pylsp_mypy.live_mode = true
# plugins.pylint.enabled = true
# plugins.pyflakes.enabled = false
# plugins.isort.enabled = true
# plugins.rope_autoimport.enabled = true
